[workspace]

members = [
    "chip_8_lib",
    "chip_8_wasm/crate",
]

# default-members = [
#     "ray_tracer_main"
# ]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true
# debug = true
